-- PLAN.md sections 3.1, 4.2, 7, and 8; BE-PLAN.md Phase B1.

create or replace function public.trg_shift_guard() returns trigger language plpgsql security definer set search_path=pg_catalog,public,app as $$ begin
  if tg_op='DELETE' then raise exception using errcode='23514',message='shift_delete_forbidden'; end if;
  if tg_table_name='shift_transitions' then if current_setting('app.transition',true) not in('shift_transition','submit_shift','recovery') then raise exception using errcode='23514',message='transition_insert_forbidden';end if;return new;end if;
  if new.station_seq<>old.station_seq or new.shift_price_map_snapshot<>old.shift_price_map_snapshot or new.shift_price_map_hash<>old.shift_price_map_hash then raise exception using errcode='23514',message='shift_immutable_fields';end if;
  if new.current_report_id is distinct from old.current_report_id and current_setting('app.transition',true)<>'submit_shift' then raise exception using errcode='23514',message='current_report_pointer_forbidden';end if;
  if new.status<>old.status and current_setting('app.transition',true) not in('shift_transition','submit_shift','recovery') then raise exception using errcode='23514',message='shift_transition_required';end if; return new; end; $$;

create policy recovery_job_shifts on public.shifts to report_writer using(true) with check(true);
create policy recovery_job_drafts on public.shift_drafts to report_writer using(true) with check(true);
create policy recovery_job_idempotency on public.submit_idempotency to report_writer using(true) with check(true);

create or replace function public.fn_recover_submitting_shifts() returns integer language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare r record; target public.shift_status; n integer:=0;
begin
  for r in select s.org_id,s.station_id,s.shift_id from public.shifts s join public.shift_drafts d using(org_id,station_id,shift_id) where s.status='submitting' and d.status='submitting' and d.updated_at < clock_timestamp()-interval '10 minutes' order by s.org_id,s.station_id,s.station_seq loop
    perform 1 from public.stations where org_id=r.org_id and station_id=r.station_id for update;
    perform 1 from public.shifts where org_id=r.org_id and station_id=r.station_id and shift_id=r.shift_id for update;
    perform 1 from public.shift_drafts where org_id=r.org_id and station_id=r.station_id and shift_id=r.shift_id for update;
    if exists(select 1 from public.shift_reports where org_id=r.org_id and station_id=r.station_id and shift_id=r.shift_id) then target:='awaiting_confirmation'; else target:='open'; end if;
    perform set_config('app.transition','recovery',true);
    update public.shifts set status=target where org_id=r.org_id and station_id=r.station_id and shift_id=r.shift_id;
    update public.shift_drafts set status=case when target='awaiting_confirmation' then 'submitted' else 'editing' end,recovery_count=recovery_count+1,updated_at=clock_timestamp() where org_id=r.org_id and station_id=r.station_id and shift_id=r.shift_id;
    insert into public.shift_transitions(org_id,station_id,shift_id,from_status,to_status,actor_user_id,reason) values(r.org_id,r.station_id,r.shift_id,'submitting',target,null,'recovery'); n:=n+1;
  end loop; return n;
end; $$;
alter function public.fn_recover_submitting_shifts() owner to report_writer;

create or replace function public.read_shift_list(p_station_id uuid default null) returns setof jsonb language plpgsql security definer set search_path=pg_catalog,public,app as $$ declare o uuid:=nullif(current_setting('app.org_id',true),'')::uuid; begin if current_setting('app.context_valid',true)<>'true' then raise exception using errcode='28000',message='request_context_required';end if; return query select jsonb_build_object('shift_id',s.shift_id::text,'station_id',s.station_id::text,'station_seq',s.station_seq::text,'business_date',s.business_date::text,'status',s.status::text,'current_report_id',s.current_report_id::text) from public.shifts s where s.org_id=o and(p_station_id is null or s.station_id=p_station_id) and(current_setting('app.station_id',true)='' or s.station_id::text=current_setting('app.station_id',true)) order by s.station_seq desc;end; $$;
alter function public.read_shift_list(uuid) owner to report_writer;
create or replace function public.read_shift_detail(p_shift_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app as $$ declare o uuid:=nullif(current_setting('app.org_id',true),'')::uuid; v jsonb; begin if current_setting('app.context_valid',true)<>'true' then raise exception using errcode='28000',message='request_context_required';end if;select jsonb_build_object('shift_id',s.shift_id::text,'station_id',s.station_id::text,'station_seq',s.station_seq::text,'opened_at',s.opened_at,'business_date',s.business_date::text,'status',s.status::text,'current_report_id',s.current_report_id::text,'draft',jsonb_build_object('draft_id',d.draft_id::text,'status',d.status::text,'revision',d.revision,'recovery_count',d.recovery_count)) into v from public.shifts s join public.shift_drafts d using(org_id,station_id,shift_id) where s.org_id=o and s.shift_id=p_shift_id and(current_setting('app.station_id',true)='' or s.station_id::text=current_setting('app.station_id',true));if v is null then raise exception using errcode='42501',message='shift_not_found';end if;return v;end; $$;
alter function public.read_shift_detail(uuid) owner to report_writer;
create or replace function public.read_report(p_report_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app as $$ declare o uuid:=nullif(current_setting('app.org_id',true),'')::uuid; v jsonb; begin if current_setting('app.context_valid',true)<>'true' then raise exception using errcode='28000',message='request_context_required';end if;select jsonb_build_object('report_id',r.report_id::text,'shift_id',r.shift_id::text,'version_no',r.version_no,'status',r.status,'submitted_at',r.submitted_at,'readings',coalesce((select jsonb_agg(jsonb_build_object('nozzle_id',x.nozzle_id::text,'meter_start',x.meter_start::text,'meter_end',x.meter_end::text,'price_used',x.price_used::text,'expected_sale_rupiah',x.expected_sale_rupiah::text) order by x.nozzle_id) from public.dispenser_readings x where x.org_id=r.org_id and x.station_id=r.station_id and x.report_id=r.report_id),'[]'::jsonb),'sales',coalesce((select jsonb_agg(jsonb_build_object('dispenser_id',x.dispenser_id::text,'cash_amount',x.cash_amount::text,'cashless_amount',x.cashless_amount::text) order by x.dispenser_id) from public.sales_declared x where x.org_id=r.org_id and x.station_id=r.station_id and x.report_id=r.report_id),'[]'::jsonb),'losses',coalesce((select jsonb_agg(jsonb_build_object('loss_id',x.loss_id::text,'direction',x.direction,'liters',x.liters::text,'cash_amount',x.cash_amount::text,'note',x.note) order by x.row_id) from public.loss_entries x where x.org_id=r.org_id and x.station_id=r.station_id and x.report_id=r.report_id),'[]'::jsonb)) into v from public.shift_reports r where r.org_id=o and r.report_id=p_report_id and(current_setting('app.station_id',true)='' or r.station_id::text=current_setting('app.station_id',true));if v is null then raise exception using errcode='42501',message='report_not_found';end if;return v;end; $$;
alter function public.read_report(uuid) owner to report_writer;

grant execute on function public.fn_recover_submitting_shifts() to pomkita_app;grant execute on function public.read_shift_list(uuid) to pomkita_app;grant execute on function public.read_shift_detail(uuid) to pomkita_app;grant execute on function public.read_report(uuid) to pomkita_app;
insert into public.procedure_registry(name,allowed_roles,action,lock_rank) values('fn_recover_submitting_shifts',array[]::text[],'recover_submitting_shifts',20),('read_shift_list',array['Supervisor','Station Admin','Owner'],'read_shift_list',20),('read_shift_detail',array['Supervisor','Station Admin','Owner'],'read_shift_detail',20),('read_report',array['Supervisor','Station Admin','Owner'],'read_report',50);
